### PR TITLE
feat: some super cool new feature! deps-dev

### PR DESCRIPTION
**Pull request by niekcandaele**

### CODE REVIEW

**Comment by niekcandaele** [comment]
Right now, the action will not merge this branch because the CI job fails. This is configured in repo settings -> branch protection rules

image

**Comment by niekcandaele** [comment]
Now, CI passed but still not merged!

It will only merge when the PR title includes 'deps-dev' (which is how Dependabot does it)

**Comment by niekcandaele** [comment]
All checks passed:
- All other CI checks are successful
- PR is labeled as 'dependencies'
- The title shows it is a dev dependency
- PR was made by approved author (in this case me, in real case it'd be dependabot)

And it gets merged :)

**Comment by StampixSMO** [comment]
I'll have a better look tomorrow, but I can't view the settings in this repo, ofc.
Also, this is on your personal account, I wouldn't be surprised that branch rules aren't enabled on private org repo's?

**Pull request merged**
